dotfiles:
  - bash_profile
  - caprc
  - gitconfig
  - gitignore
  - hgrc
  - rvmrc
  - managers

binfiles:
  - activity
  - addr
  - genpassword
  - dmg
  - gem-version
  - ramfs
  - make_ssl
  - git/git-prune-all
  - git/git-tarball
  - git/git-track
  - git/git-branches
  - git/git-clean-merged
  - git/git-churn