dotfiles:
  - bash_profile
  - caprc
  - gitconfig
  - gitignore
  - hgrc
  - rvmrc

binfiles:
  - activity
  - addr
  - feature
  - genpassword
  - static_server
  - dmg
  - gem-version
  - git/git-prune-all
  - git/git-tarball
  - git/git-track
  - git/git-branches
  - git/git-clean-merged
