dotfiles:
  - bash_profile
  - caprc
  - gemrc
  - gitconfig
  - gitignore
  - hgrc
  - rvmrc
  - managers

binfiles:
  - addr
  - genpassword
  - dmg
  - gem-version
  - ramfs
  - makessl
  - docker-clean
  - pg_url_dump
  - pg_url_load
  - dummy-commit
  - github-downloads
  - showenv
  - ipinfo
  - killspring
  - git/git-prune-all
  - git/git-tarball
  - git/git-track
  - git/git-clean-merged
  - git/git-churn
  - git/git-merge-repo
