dotfiles:
  - bash_profile
  - caprc
  - gemrc
  - gitconfig
  - gitignore
  - hgrc
  - rvmrc
  - managers

binfiles:
  - addr
  - genpassword
  - dmg
  - gem-version
  - ramfs
  - makessl
  - pg_dump_url
  - github-downloads
  - git/git-prune-all
  - git/git-tarball
  - git/git-track
  - git/git-branches
  - git/git-clean-merged
  - git/git-churn